Repository Ibotta/url_builder_app, pull requests merged in 2019-10, with the labels that each got.

#10 👾 Feature: Tests
  .babelrc
  .gitignore
  jest.config.js
  package-lock.json
  package.json
  setupTests.js
  spec/app.spec.js
  spec/context.spec.js
  spec/factories/currentUser.js
  spec/factories/customFields.js
  spec/factories/ticket.js
  spec/helpers.spec.js
  spec/mocks/clientMock.js
  spec/mocks/mock.js
  src/javascripts/lib/api.js
  src/javascripts/lib/helpers.js
  src/javascripts/modules/app.js
  src/javascripts/modules/context.js
  webpack.config.js
  yarn.lock
Labels: enhancement, review me

#9 Adding Travis CI, Code Climate, and Contributor Covenant
  .codeclimate.yml
  .gitignore
  .travis.yml
  CODE_OF_CONDUCT.md
  README.md
Labels: review me

#14 Update README and CONTRIBUTING
  .github/CONTRIBUTING.md
  README.md
  assets/app-settings-change.png
  assets/change-settings.png
  assets/example-url.png
  assets/installation-title.png
  assets/json-array-of-urls.png
  assets/links.png
  assets/screenshot-1.png
  assets/screenshot-2.png
  assets/screenshot-3.png
  assets/screenshot.png
  package-lock.json
  package.json
  src/translations/en.json
  translations/en.json
Labels: documentation, review me

#16 Check for null Organization const after API Call
  src/javascripts/modules/context.js
Labels: bug, review me

#17 Adding Zendesk Docs and Remove Private Flag
  src/ZENDESK_MANDATORY_SERVICE_TERMS
  src/manifest.json
Labels: documentation, review me

#18 Manifest Requires Private
  src/manifest.json
Labels: documentation, review me
